---
included:
  - Sources
  - Examples
excluded:
  - "**/.build"
cyclomatic_complexity:
  warning: 20
  error: 20
type_name:
  excluded:
    - ID
  allowed_symbols:
    - _
function_body_length:
  warning: 300
  error: 300
line_length:
  warning: 300
  error: 300
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
file_length:
  warning: 1000
  error: 1000
indentation_width:
  indentation_width: 4
  include_comments: false
  include_compiler_directives: false
only_rules:
#  - accessibility_label_for_image # 8 violations
#  - accessibility_trait_for_button # 6 violations
#  - anonymous_argument_in_multiline_closure # 85 violations
  - anyobject_protocol
  - array_init
#  - attributes # 255 violations
  - balanced_xctest_lifecycle
#  - blanket_disable_command # 27 violations
  - block_based_kvo
  - capture_variable
  - class_delegate_protocol
  - closing_brace
#  - closure_body_length # 37 violations
#  - closure_end_indentation # 3 violations
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma # 1 violations
  - comma_inheritance
#  - comment_spacing # 37 violations
  - compiler_protocol_init
  - computed_accessors_order
#  - conditional_returns_on_newline # 3 violations
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type # 1 violations
  - custom_rules
#  - cyclomatic_complexity # 4 violations
  - deployment_target
#  - direct_return # 28 violations
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_direct_init
#  - discouraged_none_name # 4 violations
  - discouraged_object_literal
  - discouraged_optional_boolean
#  - discouraged_optional_collection # 12 violations
  - duplicate_conditions
  - duplicate_enum_cases
  - duplicate_imports
  - duplicated_key_in_dictionary_literal
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
#  - explicit_acl # 1750 violations
#  - explicit_enum_raw_value # 17 violations
  - explicit_init
  - explicit_self
#  - explicit_top_level_acl # 262 violations
#  - explicit_type_interface # 2095 violations
#  - extension_access_modifier # 8 violations
  - fallthrough
#  - fatal_error_message # 80 violations
  - file_header
#  - file_length # 5 violations
#  - file_name # 94 violations
  - file_name_no_space
#  - file_types_order # 280 violations
#  - final_test_case # 9 violations
  - first_where
  - flatmap_over_map_reduce
#  - for_where # 4 violations
#  - force_cast # 14 violations
#  - force_try # 47 violations
#  - force_unwrapping # 253 violations
#  - function_body_length # 8 violations
#  - function_default_parameter_at_end # 52 violations
  - function_parameter_count # 1 violations
  - generic_type_name
  - ibinspectable_in_extension
  - identical_operands
#  - identifier_name # 729 violations
  - implicit_getter
#  - implicit_return # 14 violations
#  - implicitly_unwrapped_optional # 10 violations
  - inclusive_language
#  - indentation_width # 110 violations
  - inert_defer
  - invalid_swiftlint_command
  - is_disjoint
  - joined_default_parameter
#  - large_tuple # 46 violations
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
#  - legacy_multiple # 5 violations
  - legacy_nsgeometry_functions
  - legacy_objc_type
  - legacy_random
#  - let_var_whitespace # 24 violations
#  - line_length # 538 violations
  - literal_expression_end_indentation
  - local_doc_comment # 1 violations
  - lower_acl_than_parent
  - mark
#  - missing_docs # 1321 violations
  - modifier_order
#  - multiline_arguments # 18 violations
#  - multiline_arguments_brackets # 49 violations
#  - multiline_function_chains # 26 violations
  - multiline_literal_brackets
  - multiline_parameters
#  - multiline_parameters_brackets # 10 violations
  - multiple_closures_with_trailing_closure
#  - nesting # 20 violations
  - nimble_operator
#  - no_extension_access_modifier # 381 violations
  - no_fallthrough_only
#  - no_grouping_extension # 255 violations
#  - no_magic_numbers # 1519 violations
  - no_space_in_method_call
  - non_optional_string_data_conversion # 2 violations
  - non_overridable_class_declaration
  - notification_center_detachment
  - ns_number_init_as_function_reference
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - nsobject_prefer_isequal
#  - number_separator # 3 violations
  - object_literal
#  - one_declaration_per_file # 175 violations
#  - opening_brace # 4 violations
#  - operator_usage_whitespace # 3 violations
#  - operator_whitespace # 6 violations
  - optional_enum_case_matching
  - orphaned_doc_comment
  - overridden_super_call
  - override_in_extension
#  - pattern_matching_keywords # 39 violations
  - period_spacing
#  - prefer_nimble # 87 violations
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init # 1 violations
#  - prefixed_toplevel_constant # 5 violations
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_subject
#  - private_swiftui_state # 127 violations
  - private_unit_test
  - prohibited_interface_builder
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into # 2 violations
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
#  - redundant_self_in_closure # 6 violations
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation # 2 violations
  - redundant_void_return
#  - required_deinit # 30 violations
  - required_enum_case
  - return_arrow_whitespace
  - return_value_from_void_function
  - self_binding
  - self_in_property_initialization
  - shorthand_argument # 2 violations
  - shorthand_operator # 1 violations
  - shorthand_optional_binding
#  - single_test_class # 7 violations
#  - sorted_enum_cases # 48 violations
  - sorted_first_last
#  - sorted_imports # 57 violations
#  - statement_position # 149 violations
  - static_operator
  - static_over_final_class
  - strict_fileprivate # 1 violations
  - strong_iboutlet
#  - superfluous_disable_command # 9 violations
#  - superfluous_else # 44 violations
#  - switch_case_alignment # 3 violations
#  - switch_case_on_newline # 67 violations
  - syntactic_sugar
#  - test_case_accessibility # 3 violations
#  - todo # 219 violations
  - toggle_bool
#  - trailing_closure # 47 violations
#  - trailing_comma # 116 violations
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
#  - type_contents_order # 290 violations
#  - type_name # 6 violations
  - typesafe_array_init
  - unavailable_condition
#  - unavailable_function # 14 violations
  - unhandled_throwing_task # 1 violations
  - unneeded_break_in_switch
  - unneeded_override
  - unneeded_parentheses_in_closure_argument
  - unneeded_synthesized_initializer
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
#  - unused_closure_parameter # 6 violations
  - unused_control_flow_label
  - unused_declaration
  - unused_enumerated # 1 violations
  - unused_import
  - unused_optional_binding
  - unused_setter_value # 2 violations
  - valid_ibinspectable
  - vertical_parameter_alignment
#  - vertical_parameter_alignment_on_call # 4 violations
#  - vertical_whitespace # 37 violations
#  - vertical_whitespace_between_cases # 617 violations
#  - vertical_whitespace_closing_braces # 34 violations
#  - vertical_whitespace_opening_braces # 30 violations
  - void_function_in_ternary
  - void_return
  - weak_delegate
  - xct_specific_matcher
  - xctfail_message
  - yoda_condition
