included:
    - Sources
    - Examples
excluded:
    - "**/.build"
analyzer_rules:
    - capture_variable
    - explicit_self
    - typesafe_array_init
    - unused_declaration
    - unused_import
only_rules:
    # - accessibility_label_for_image # TODO:
    # - accessibility_trait_for_button # TODO:
    # - anonymous_argument_in_multiline_closure  # TODO:
    # - anyobject_protocol # NOPE
    - array_init
    - balanced_xctest_lifecycle
    # - blanket_disable_command # NOPE
    - block_based_kvo
    - class_delegate_protocol
    - closing_brace
    # - closure_body_length # NOPE
    - closure_end_indentation
    - closure_parameter_position
    - closure_spacing
    - collection_alignment
    - colon
    - comma
    - comma_inheritance
    - comment_spacing
    - compiler_protocol_init
    - computed_accessors_order
    # - conditional_returns_on_newline # TODO:
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - control_statement
    - convenience_type
    - custom_rules
    - cyclomatic_complexity
    - deployment_target
    # - direct_return # TODO:
    - discarded_notification_center_observer
    - discouraged_assert
    - discouraged_direct_init
    # - discouraged_none_name # NOPE
    - discouraged_object_literal
    - discouraged_optional_boolean
    # - discouraged_optional_collection # NOPE
    - duplicate_conditions
    - duplicate_enum_cases
    - duplicate_imports
    - duplicated_key_in_dictionary_literal
    - dynamic_inline
    - empty_collection_literal
    - empty_count
    - empty_enum_arguments
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - empty_string
    - empty_xctest_method
    - enum_case_associated_values_count
    - expiring_todo
    # - explicit_acl # TODO: Nice to have but too many violations.
    # - explicit_enum_raw_value: NOPE
    - explicit_init
    # - explicit_top_level_acl # TODO: Nice to have but too many violations.
    # - explicit_type_interface # NOPE
    - extension_access_modifier
    # - fallthrough # NOPE
    # - fatal_error_message # TODO:
    # - file_header  # TODO:
    - file_length  # TODO:
    # - file_name  # TODO:
    - file_name_no_space
    # - file_types_order # NOPE (MAYBE)
    - first_where
    - flatmap_over_map_reduce
    - for_where
    # - force_cast  # TODO:
    # - force_try  # TODO:
    #- force_unwrapping # TODO:
    - function_body_length  # TODO:
    # - function_default_parameter_at_end # NOPE
    - function_parameter_count
    - generic_type_name
    - ibinspectable_in_extension
    - identical_operands
    #- identifier_name # NOPE
    - implicit_getter
    - implicit_return
    # - implicitly_unwrapped_optional  # TODO:
    - inclusive_language
    # - indentation_width
    # - inert_defer # NOPE
    - invalid_swiftlint_command
    - is_disjoint
    - joined_default_parameter
    # - large_tuple # NOPE
    - last_where
    # - leading_whitespace  # TODO:
    - legacy_cggeometry_functions
    - legacy_constant
    - legacy_constructor
    - legacy_hashing
    # - legacy_multiple  # TODO:
    - legacy_nsgeometry_functions
    - legacy_objc_type
    - legacy_random
    # - let_var_whitespace # NOPE
    - line_length
    - literal_expression_end_indentation
    - local_doc_comment
    - lower_acl_than_parent
    - mark
    # - missing_docs  # TODO:
    - modifier_order
    # - multiline_arguments # NOPE
    # - multiline_arguments_brackets # NOPE
    # - multiline_function_chains  # TODO:
    - multiline_literal_brackets
    - multiline_parameters
    # - multiline_parameters_brackets # NOPE
    - multiple_closures_with_trailing_closure
    # - nesting # NOPE
    - nimble_operator
    # - no_extension_access_modifier  # TODO:
    - no_fallthrough_only
    # - no_grouping_extension # NOPE
    # - no_magic_numbers # NOPE
    - no_space_in_method_call
    - non_overridable_class_declaration
    - notification_center_detachment
    - ns_number_init_as_function_reference
    - nslocalizedstring_key
    - nslocalizedstring_require_bundle
    - nsobject_prefer_isequal
    - number_separator
    - object_literal
    - opening_brace
    - operator_usage_whitespace
    - operator_whitespace
    - optional_enum_case_matching
    - orphaned_doc_comment
    - overridden_super_call
    - override_in_extension
    # - pattern_matching_keywords # NOPE
    - period_spacing
    # - prefer_nimble # TODO: MAYBE
    - prefer_self_in_static_references
    - prefer_self_type_over_type_of_self
    - prefer_zero_over_explicit_init
    # - prefixed_toplevel_constant # NOPE
    - private_action
    - private_outlet
    - private_over_fileprivate
    - private_subject
    # - private_swiftui_state  # TODO:
    - private_unit_test
    - prohibited_interface_builder
    - prohibited_super_call
    - protocol_property_accessors_order
    - quick_discouraged_call
    - quick_discouraged_focused_test
    - quick_discouraged_pending_test
    - raw_value_for_camel_cased_codable_enum
    - reduce_boolean
    - reduce_into
    - redundant_discardable_let
    - redundant_nil_coalescing
    - redundant_objc_attribute
    - redundant_optional_initialization
    - redundant_self_in_closure
    - redundant_set_access_control
    - redundant_string_enum_value
    - redundant_type_annotation
    - redundant_void_return
    # - required_deinit # NOPE
    - required_enum_case
    - return_arrow_whitespace
    - return_value_from_void_function
    - self_binding
    - self_in_property_initialization
    - shorthand_operator
    - shorthand_optional_binding
    - single_test_class
    # - sorted_enum_cases # NOPE
    - sorted_first_last
    - sorted_imports
    # - statement_position # NOPE
    - static_operator
    # - strict_fileprivate  # NOPE
    - strong_iboutlet
    # - superfluous_disable_command # TODO
    # - superfluous_else # Nice to have. Too many offenders.
    - switch_case_alignment
    - switch_case_on_newline
    - syntactic_sugar
    - test_case_accessibility
    # - todo  # TODO:
    - toggle_bool
    # - trailing_closure  # TODO:
    # - trailing_comma # NOPE
    - trailing_newline
    - trailing_semicolon
    - trailing_whitespace
    - type_body_length
    # - type_contents_order  # NOPE (Maybe)
    - type_name
    - unavailable_condition
    # - unavailable_function # TODO:
    - unhandled_throwing_task
    - unneeded_break_in_switch
    - unneeded_override
    - unneeded_parentheses_in_closure_argument
    - unneeded_synthesized_initializer
    - unowned_variable_capture
    # - untyped_error_in_catch  # TODO:
    # - unused_capture_list  # TODO:
    - unused_closure_parameter
    - unused_control_flow_label
    - unused_enumerated
    - unused_optional_binding
    - unused_setter_value
    - valid_ibinspectable
    - vertical_parameter_alignment
    - vertical_parameter_alignment_on_call
    - vertical_whitespace
    #- vertical_whitespace_between_cases  # NOPE
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - void_function_in_ternary
    - void_return
    - weak_delegate
    - xct_specific_matcher
    - xctfail_message
    - yoda_condition

cyclomatic_complexity:
    warning: 20
    error: 20

type_name:
    excluded: ["ID"]
    allowed_symbols: ["_"]

function_body_length:
    warning: 300 # TODO: Reduce. Default is 50.
    error: 300

line_length:
    warning: 300 # TODO: Reduce.
    error: 300
    ignores_urls: true
    ignores_function_declarations: true
    ignores_comments: true
    ignores_interpolated_strings: true

file_length:
    warning: 1000 # TODO: Reduce.
    error: 1000
