name: Swift
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: macos-14 # macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.3.0 # latest
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
