name: Swift
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: macos-14 # macos-latest
    steps:
      - name: Install Xcode.
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.3.0 # latest
      - name: Install just.
        uses: extractions/setup-just@v1
      - name: Checkout source.
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build.
        run: swift build -v
      - name: Run tests.
        run: swift test -v
    #   - name: Build examples.
    #     run: just build-examples
